### ISSUE TITLE
syslog4j-0.9.55, compatibility issue with JNA-4.1

### ISSUE THREAD

**Issue by raghsriniv** [graylog-labs/syslog4j-graylog2#22]
I ran into this issue when I attempted to move from JNA 3.4.0 to 4.1.0.
I suspect we'd have the same issue with the latest release (0.9.60?) as well given that SockAddr imp under org.graylog2.syslog4j.impl.unix.socket.UnixSocketSyslog hasn't changed.

```
Caused by: java.lang.Error: Structure.getFieldOrder() on class org.graylog2.syslog4j.impl.unix.socket.UnixSocketSyslog$SockAddr does not provide enough names ([]) to match declared fields ([sun_family, sun_path])
at com.sun.jna.Structure.getFields(Structure.java:913)
at com.sun.jna.Structure.deriveLayout(Structure.java:1058)
at com.sun.jna.Structure.calculateSize(Structure.java:982)
at com.sun.jna.Structure.allocateMemory(Structure.java:363)
at com.sun.jna.Structure.ensureAllocated(Structure.java:339)
at com.sun.jna.Structure.ensureAllocated(Structure.java:329)
at com.sun.jna.Structure.size(Structure.java:393)
at org.graylog2.syslog4j.impl.unix.socket.UnixSocketSyslog.connect(UnixSocketSyslog.java:109)
at org.graylog2.syslog4j.impl.unix.socket.UnixSocketSyslog.write(UnixSocketSyslog.java:119)
at org.graylog2.syslog4j.impl.AbstractSyslog.write(AbstractSyslog.java:317)
at org.graylog2.syslog4j.impl.AbstractSyslog.log(AbstractSyslog.java:253)
at org.graylog2.syslog4j.impl.AbstractSyslog.log(AbstractSyslog.java:124)
```

**Comment by joschi** [comment]
@raghsriniv We're only using some parts of syslog4j in Graylog and the server implementations are **not** part of that and we have no interest in fixing issues in these parts ourselves.

If you intend to use the syslog4j server implementations, I recommend switching to another fork of syslog4j, e. g. https://github.com/NessComputing/syslog4j

This being said, feel free to provide a pull request to fix this issue.

**Comment by raghsriniv** [comment]
@joschi  I have the fix, happy to send a pull request. Please allow me to push my branch so I may create a pull request.

**Comment by raghsriniv** [comment]
@joschi: please let me know if there is any interest in accepting my fix, or I could close this issue out.

**Comment by joschi** [comment]
@raghsriniv Please refer to https://help.github.com/articles/about-pull-requests/ for instructions how to create a pull request in a project on GitHub.

**Comment by raghsriniv** [comment]
@joschi 
It appears I do not have permission to push a branch to graylog-labs/syslog4j-graylog2.git repo:
-
~/src/syslog4j-graylog2$ git  push  origin unix_socket_sockaddr_fix

ERROR: Permission to graylog-labs/syslog4j-graylog2.git denied to raghsriniv.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

~/src/syslog4j-graylog2$ git remote -v
origin	git@github.com:graylog-labs/syslog4j-graylog2.git (fetch)
origin	git@github.com:graylog-labs/syslog4j-graylog2.git (push)

-

I have no problem pushing to my own repo on github using the same credentials.

**Comment by raghsriniv** [comment]
@joschi you need to add me, @raghsriniv, to the collaborator list for this repo.

**Comment by joschi** [comment]
@raghsriniv Fork this repo, make your changes, and create a pull request in this repository.
