### ISSUE TITLE
It complains by emitting the SyslogRuntimeException: "UnixSyslog not supported on non-Unix platforms" on OpenBSD.

### ISSUE THREAD

**Issue by rgolubtsov** [graylog-labs/syslog4j-graylog2#26]
**Preamble:**

1. The target OS to build and run is **OpenBSD/amd64 6.3**.
2. The application utilizing the `syslog4j` package is written in **Clojure** and the affected module is accessible [here](https://github.com/rgolubtsov/dnsresolvd-multilang/blob/master/src/clojure/dnsresolvd).
3. This application has been tested on **Ubuntu Server** (Ubuntu 16.04.6 LTS x86-64) as well as on **Arch Linux** (kernel 5.0.2-arch1-1-ARCH x86-64), and I claim &ndash; regarding using the **UnixSyslog** facility, &ndash; it is working well: i.e. it is opening, writing to, and closing the system logger as expected, without any exceptions or errors when running on the aforementioned OSes.

**Actual behaviour when using the UnixSyslog facility on OpenBSD:**

When calling its constructor &ndash; `UnixSyslog` &ndash; it produces the `org.graylog2.syslog4j.SyslogRuntimeException`:

```
Exception in thread "main" org.graylog2.syslog4j.SyslogRuntimeException: UnixSyslog not supported on non-Unix platforms, compiling:(/home/<username>/dnsresolvd-multilang/src/clojure/./dnsresolvd:171:3)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.main$load_script.invokeStatic(main.clj:275)
        at clojure.main$script_opt.invokeStatic(main.clj:335)
        at clojure.main$script_opt.invoke(main.clj:330)
        at clojure
```

**Expected behaviour when using the UnixSyslog facility on OpenBSD:**

Do not emit the `SyslogRuntimeException` exception, but simply open the system logger and write to it wherever indicated in the application code (just like it is tested on **Ubuntu Server** and **Arch Linux**, stated above).

**Quick investigation for the root cause:**

It seems that this exception is caused by the following piece of [code](https://github.com/graylog-labs/syslog4j-graylog2/blob/30ee33066eec5fdb0656f0f948900f5b2905d32c/src/main/java/org/graylog2/syslog4j/impl/unix/UnixSyslog.java#L48):

```
        if (!OSDetectUtility.isUnix()) {
            throw new SyslogRuntimeException("UnixSyslog not supported on non-Unix platforms");
        }
```

**OpenBSD** is in fact a _Unix-like_ operating system. But the `OSDetectUtility.isUnix()` method doesn't know anything about that. :point_left:

**Comment by rgolubtsov** [comment]
Close due to [this](https://github.com/graylog-labs/syslog4j-graylog2/pull/27) fix, which is merged and is quite sufficient.
